/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Obs */
        get: operations["get_obs_api_observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulate/beredskap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Beredskap */
        post: operations["simulate_beredskap_api_simulate_beredskap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Costs */
        get: operations["get_costs_api_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treatment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Treatment */
        get: operations["get_treatment_api_treatment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bydel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bydel */
        get: operations["get_bydel_api_bydel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeredskapsRequest */
        BeredskapsRequest: {
            /** Buildings */
            buildings: components["schemas"]["BuildingInput"][];
            /** Tank Liters */
            tank_liters: number;
            /** Population */
            population: number;
            /**
             * Efficiency
             * @default 0.85
             */
            efficiency: number;
            /**
             * Usage Level
             * @default survival_total
             */
            usage_level: string;
            /**
             * Climate Scenario
             * @default historical
             */
            climate_scenario: string;
            /**
             * Station
             * @default SN50540
             */
            station: string;
        };
        /** BeredskapsResponse */
        BeredskapsResponse: {
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Simulation Series */
            simulation_series: components["schemas"]["SimulationRow"][];
            /** Dry Spells */
            dry_spells: components["schemas"]["DrySpell"][];
            /** Scenario Comparison */
            scenario_comparison?: components["schemas"]["ScenarioComparison"][] | null;
            /**
             * Yearly Outcomes
             * @default []
             */
            yearly_outcomes: components["schemas"]["YearlyOutcome"][];
        };
        /** BuildingInput */
        BuildingInput: {
            /** Name */
            name: string;
            /** Roof Area M2 */
            roof_area_m2: number;
            /**
             * Height M
             * @default 5
             */
            height_m: number;
        };
        /** BuildingPreset */
        BuildingPreset: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Roof Area M2 */
            roof_area_m2: number;
            /** Default People */
            default_people: number;
            /** Height M */
            height_m: number;
            /** Description */
            description: string;
        };
        /** BydelResponse */
        BydelResponse: {
            /** Bydeler */
            bydeler: components["schemas"]["BydelRow"][];
            /** Participation Pct */
            participation_pct: number;
            /** Total Daily Liters */
            total_daily_liters: number;
            /** Total Demand Liters */
            total_demand_liters: number;
            /** Demand Coverage Pct */
            demand_coverage_pct: number;
            /** Assumptions */
            assumptions: string[];
        };
        /** BydelRow */
        BydelRow: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Population */
            population: number;
            /** Suitable Roof M2 */
            suitable_roof_m2: number;
            /** Daily Yield Liters */
            daily_yield_liters: number;
            /** Demand Liters */
            demand_liters: number;
            /** Coverage Pct */
            coverage_pct: number;
        };
        /** ClimateScenario */
        ClimateScenario: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Intensity Factor */
            intensity_factor: number;
            /** Dry Spell Factor */
            dry_spell_factor: number;
        };
        /**
         * ConfigDefaults
         * @description Shared domain defaults — the frontend reads these instead of
         *     hardcoding mirrors of backend constants.
         */
        ConfigDefaults: {
            /**
             * Collection Efficiency
             * @default 0.85
             */
            collection_efficiency: number;
            /**
             * Building Height M
             * @default 5
             */
            building_height_m: number;
            /**
             * Annual Rainfall Mm
             * @default 2250
             */
            annual_rainfall_mm: number;
            /**
             * Tank Recommendation Days
             * @default [
             *       7,
             *       30,
             *       60
             *     ]
             */
            tank_recommendation_days: number[];
            /**
             * Station Id
             * @default SN50540
             */
            station_id: string;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Scales */
            scales: components["schemas"]["ScaleSchema"][];
            /** Scale Presets */
            scale_presets: {
                [key: string]: string[];
            };
            /** Building Presets */
            building_presets: components["schemas"]["BuildingPreset"][];
            /** Infrastructure Facilities */
            infrastructure_facilities: components["schemas"]["InfrastructureFacility"][];
            /** Climate Scenarios */
            climate_scenarios: components["schemas"]["ClimateScenario"][];
            /** Water Needs */
            water_needs: {
                [key: string]: number;
            };
            defaults: components["schemas"]["ConfigDefaults"];
            /** Roof Materials */
            roof_materials: components["schemas"]["RoofMaterial"][];
            /** Stations */
            stations: components["schemas"]["StationSchema"][];
        };
        /** CostBreakdownItem */
        CostBreakdownItem: {
            /** Category */
            category: string;
            /** Amount */
            amount: number;
        };
        /** CostEstimateRow */
        CostEstimateRow: {
            /** Label */
            label: string;
            /** Capital Low */
            capital_low: number;
            /** Capital High */
            capital_high: number;
            /** Annual Operating Low */
            annual_operating_low: number;
            /** Annual Operating High */
            annual_operating_high: number;
            /** Capacity Low */
            capacity_low: number;
            /** Capacity High */
            capacity_high: number;
        };
        /** CostsResponse */
        CostsResponse: {
            /** Estimate Label */
            estimate_label: string;
            /** Capital Low */
            capital_low: number;
            /** Capital High */
            capital_high: number;
            /** Annual Op Low */
            annual_op_low: number;
            /** Annual Op High */
            annual_op_high: number;
            /** Capital */
            capital: number;
            /** Annual Op */
            annual_op: number;
            /** Cost Per Person */
            cost_per_person: number;
            /** Lifecycle 10 */
            lifecycle_10: number;
            /** Lifecycle 20 */
            lifecycle_20: number;
            /** Lifecycle 30 */
            lifecycle_30: number;
            /** Cost Per Liter 20 */
            cost_per_liter_20: number | null;
            /** Capital Breakdown */
            capital_breakdown: components["schemas"]["CostBreakdownItem"][];
            /** Operating Breakdown */
            operating_breakdown: components["schemas"]["CostBreakdownItem"][];
            /** All Estimates */
            all_estimates: components["schemas"]["CostEstimateRow"][];
        };
        /** DrySpell */
        DrySpell: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Days */
            days: number;
            /** Total Rain Mm */
            total_rain_mm: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InfrastructureFacility */
        InfrastructureFacility: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Roof Area M2 */
            roof_area_m2: number;
            /** Default People */
            default_people: number;
            /** Height M */
            height_m: number;
            /** Description */
            description: string;
        };
        /** Observation */
        Observation: {
            /** Date */
            date: string;
            /** Precipitation Mm */
            precipitation_mm: number;
            /** Air Temperature C */
            air_temperature_c?: number | null;
        };
        /** RoofMaterial */
        RoofMaterial: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Risk Class */
            risk_class: string;
            /** Description */
            description: string;
        };
        /** ScaleSchema */
        ScaleSchema: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Typical Population */
            typical_population: number[];
            /** Typical Tank Liters */
            typical_tank_liters: number[];
            /** Typical Buildings */
            typical_buildings: number[];
            /** Treatment Level */
            treatment_level: string;
            /** Governance Note */
            governance_note: string;
            /** Cost Range Nok */
            cost_range_nok: number[];
        };
        /** ScenarioComparison */
        ScenarioComparison: {
            /** Scenario */
            scenario: string;
            /** Label */
            label: string;
            /** Total Precip Mm */
            total_precip_mm: number;
            /** Dry Days */
            dry_days: number;
            /** Longest Dry Spell */
            longest_dry_spell: number;
        };
        /** SimulationRow */
        SimulationRow: {
            /** Date */
            date: string;
            /** Precipitation Mm */
            precipitation_mm: number;
            /** Tank Pct */
            tank_pct: number;
            /** Tank Level Liters */
            tank_level_liters: number;
            /** Days Remaining */
            days_remaining: number;
        };
        /** StationSchema */
        StationSchema: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Note */
            note: string;
        };
        /** TreatmentResponse */
        TreatmentResponse: {
            /** Material */
            material: string;
            /** Material Label */
            material_label: string;
            /** Risk Class */
            risk_class: string;
            /** Potable */
            potable: boolean;
            /** Barriers */
            barriers: string[];
            /** Cost Low Nok */
            cost_low_nok: number;
            /** Cost High Nok */
            cost_high_nok: number;
            /** Note */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YearlyOutcome */
        YearlyOutcome: {
            /** Year */
            year: number;
            /** Total Collected Liters */
            total_collected_liters: number;
            /** Days Tank Empty */
            days_tank_empty: number;
            /** Min Tank Pct */
            min_tank_pct: number;
            /** Longest Dry Spell Days */
            longest_dry_spell_days: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    get_obs_api_observations_get: {
        parameters: {
            query?: {
                days?: number;
                station?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_beredskap_api_simulate_beredskap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeredskapsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeredskapsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_costs_api_costs_get: {
        parameters: {
            query: {
                population: number;
                scale?: string;
                annual_liters?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_treatment_api_treatment_get: {
        parameters: {
            query: {
                material: string;
                scale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreatmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bydel_api_bydel_get: {
        parameters: {
            query?: {
                participation?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BydelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
